apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prestashop-update-deployments
  namespace: woocommerce-testshop
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  - statefulsets/scale
  - deployments/scale
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch