---
# Source: prestashop/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: prestashop-dev3c-app-secret
  namespace: "woocommerce-testshop"
  labels:
    app.kubernetes.io/name: prestashop
    helm.sh/chart: prestashop-16.0.0
    app.kubernetes.io/instance: prestashop-dev3c
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  prestashop-password: "SuperSecretPass"
---
# Source: prestashop/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: prestashopdb-dev3c-externaldb
  namespace: "woocommerce-testshop"
  labels:
    app.kubernetes.io/name: prestashop
    helm.sh/chart: prestashop-16.0.0
    app.kubernetes.io/instance: prestashop-dev3c
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  db-password: "SuperSecretPass"