apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

helmGlobals:
  chartHome: ../../base/15.3.6

nameSuffix: -dev3c

commonLabels:
  app.kubernetes.io/instance: prestashop-dev3c

helmCharts:
- name: prestashop
  repo: https://charts.bitnami.com/bitnami
  version: 15.3.6
  includeCRDs: true
  releaseName: prestashop
  namespace: woocommerce-testshop
  valuesInline:
    mariadb:
      enabled: false
    externalDatabase:
      host: woocommercedb.utils.internal
      port: 3306
      user: prestashopdb-dev3c
      database: prestashopdb-dev3c
      existingSecret: prestashop-externaldb
      # password: SuperSecretPass
    persistence:
      enabled: true
      storageClass: gp3-retain
    service:
      type: NodePort
    prestashopHost: prestashop-testshop-dev3c.payeye.com
    prestashopUsername: prestashop-dev3c@payeye.com
    existingSecret: true
    # prestashopPassword: SuperSecretPass
    prestashopEmail: bartosz.bury@payeye.com
    prestashopFirstName: Payeye
    prestashopLastName: User
    prestashopCountry: pl
    prestashopLanguage: pl


# FIX for already created PVC resource with diffrent name
replacements:
- source:
    kind: Deployment
    fieldPath: metadata.labels.app\.kubernetes\.io/instance
    options:
      delimiter: '-'
      index: 1
  targets:
  - select:
      kind: PersistentVolumeClaim
    fieldPaths:
      - metadata.name
    options:
      delimiter: '-'
      index: 1
- source:
    kind: Deployment
    fieldPath: metadata.labels.app\.kubernetes\.io/instance
    options:
      delimiter: '-'
      index: 0
  targets:
  - select:
      kind: PersistentVolumeClaim
    fieldPaths:
      - metadata.name
    options:
      delimiter: '-'
      index: 2