apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

helmGlobals:
  chartHome: ../../base/15.3.6

nameSuffix: -uat3b

commonLabels:
  app.kubernetes.io/instance: prestashop-uat3b

helmCharts:
- name: prestashop
  repo: https://charts.bitnami.com/bitnami
  version: 15.3.6
  includeCRDs: true
  releaseName: prestashop
  namespace: woocommerce-testshop
  valuesInline:
    mariadb:
      enabled: false
    externalDatabase:
      host: woocommercedb.utils.internal
      port: 3306
      user: prestashopdb-uat3b
      database: prestashopdb-uat3b
      existingSecret: prestashop-externaldb
      # password: SuperSecretPass
    persistence:
      enabled: true
      storageClass: gp3-retain
    service:
      type: NodePort
    prestashopHost: prestashop-testshop-uat3b.payeye.com
    prestashopUsername: prestashop-uat3b@payeye.com
    existingSecret: true
    # prestashopPassword: SuperSecretPass
    prestashopEmail: bartosz.bury@payeye.com
    prestashopFirstName: Payeye
    prestashopLastName: User
    prestashopCountry: pl
    prestashopLanguage: pl
